# Generated by Django 4.2.19 on 2025-04-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='ที่อยู่')),
                ('phone', models.CharField(max_length=50, verbose_name='เบอร์โทร')),
                ('email', models.EmailField(max_length=254, verbose_name='อีเมล')),
            ],
        ),
    ]
